# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git_project\ToDoList\ui\FootWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FootWidget(object):
    def setupUi(self, FootWidget):
        FootWidget.setObjectName("FootWidget")
        FootWidget.resize(404, 40)
        FootWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalLayout = QtWidgets.QHBoxLayout(FootWidget)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnKanBan = QtWidgets.QPushButton(FootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnKanBan.sizePolicy().hasHeightForWidth())
        self.btnKanBan.setSizePolicy(sizePolicy)
        self.btnKanBan.setObjectName("btnKanBan")
        self.horizontalLayout.addWidget(self.btnKanBan)
        self.btnToDo = QtWidgets.QPushButton(FootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnToDo.sizePolicy().hasHeightForWidth())
        self.btnToDo.setSizePolicy(sizePolicy)
        self.btnToDo.setObjectName("btnToDo")
        self.horizontalLayout.addWidget(self.btnToDo)
        self.btnComplete = QtWidgets.QPushButton(FootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnComplete.sizePolicy().hasHeightForWidth())
        self.btnComplete.setSizePolicy(sizePolicy)
        self.btnComplete.setObjectName("btnComplete")
        self.horizontalLayout.addWidget(self.btnComplete)
        self.btnSetting = QtWidgets.QPushButton(FootWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetting.sizePolicy().hasHeightForWidth())
        self.btnSetting.setSizePolicy(sizePolicy)
        self.btnSetting.setObjectName("btnSetting")
        self.horizontalLayout.addWidget(self.btnSetting)

        self.retranslateUi(FootWidget)
        QtCore.QMetaObject.connectSlotsByName(FootWidget)

    def retranslateUi(self, FootWidget):
        _translate = QtCore.QCoreApplication.translate
        FootWidget.setWindowTitle(_translate("FootWidget", "foot"))
        self.btnKanBan.setText(_translate("FootWidget", "看板"))
        self.btnToDo.setText(_translate("FootWidget", "待办"))
        self.btnComplete.setText(_translate("FootWidget", "已完成"))
        self.btnSetting.setText(_translate("FootWidget", "设置"))
