# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git_project\ToDoList\ui\KanBanWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KanBanWidget(object):
    def setupUi(self, KanBanWidget):
        KanBanWidget.setObjectName("KanBanWidget")
        KanBanWidget.resize(400, 603)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(KanBanWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainVLayout = QtWidgets.QVBoxLayout()
        self.mainVLayout.setObjectName("mainVLayout")
        self.verticalLayout_2.addLayout(self.mainVLayout)

        self.retranslateUi(KanBanWidget)
        QtCore.QMetaObject.connectSlotsByName(KanBanWidget)

    def retranslateUi(self, KanBanWidget):
        _translate = QtCore.QCoreApplication.translate
        KanBanWidget.setWindowTitle(_translate("KanBanWidget", "kanban"))
